# Find ICONV library
# 
# input:
#  ICONV_ROOT
#
# output:
#  ICONV_FOUND
#  ICONV_INCLUDE_DIR
#  ICONV_LIBRARIES
#

if(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)
    set(ICONV_FIND_QUITELY TRUE) # cached
endif(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)

if(NOT DEFINED ICONV_ROOT)
    set(ICONV_ROOT /usr /usr/local $ENV{ICONV_ROOT})
endif(NOT DEFINED ICONV_ROOT)

find_path(ICONV_INCLUDE_DIR iconv.h
    PATHS ${ICONV_ROOT}
    PATH_SUFFIXES include
)

find_library(ICONV_LIBRARIES
    NAMES iconv
    PATHS ${ICONVROOT}
    ICONV_SUFFIXES lib
)
mark_as_advanced(ICONV_INCLUDE_DIR ICONV_LIBRARIES)


include("${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake")
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ICONV DEFAULT_MSG ICONV_INCLUDE_DIR ICONV_LIBRARIES)


